packer_dir := "vm/packer"
tf_dir     := "vm/terraform"
state_file := tf_dir / "stopped.auto.tfvars"

_default:
    @just --list --unsorted

# build the devstation AMI (packer + ansible)
ami:
    cd {{packer_dir}} && packer init . && packer build devstation.pkr.hcl

# stamp out the nodes
up:
    cd {{tf_dir}} && terraform init -input=false && terraform apply -auto-approve

# destroy the nodes, disks included
[confirm]
down:
    cd {{tf_dir}} && terraform destroy -auto-approve
    rm -f {{state_file}}

# stop nodes but keep their disks: `just stop 1 2`
stop +nodes:
    #!/usr/bin/env bash
    set -eu
    just _check {{nodes}}
    echo "stopped_nodes = [$(echo $(just _stopped) {{nodes}} | tr ' ' '\n' | grep -v '^$' | sort -nu | paste -sd, -)]" > {{state_file}}
    just _apply
    just ip

# bring stopped nodes back: `just start 1`
start +nodes:
    #!/usr/bin/env bash
    set -eu
    just _check {{nodes}}
    keep=$(echo $(just _stopped) | tr ' ' '\n' | grep -vxF -f <(echo {{nodes}} | tr ' ' '\n') || true)
    echo "stopped_nodes = [$(echo $keep | tr ' ' '\n' | grep -v '^$' | sort -nu | paste -sd, -)]" > {{state_file}}
    just _apply
    just ip

# print node name -> public IP, or 'stopped'
ip:
    @cd {{tf_dir}} && terraform apply -refresh-only -auto-approve >/dev/null && terraform output nodes

# open VSCode on a node over Remote-SSH: `just code 0`
code node:
    #!/usr/bin/env bash
    set -eu
    just _check {{node}}
    just ip >/dev/null   # refreshes state, so the IP below is never stale
    host="$(cd {{tf_dir}} && terraform output -raw node_prefix)-{{node}}"
    addr=$(cd {{tf_dir}} && terraform output -json nodes | jq -r --arg h "$host" '.[$h]')
    if [ "$addr" = "stopped" ]; then
        echo "$host is stopped: bring it back with 'just start {{node}}'" >&2
        exit 1
    fi
    just _sshsync
    code --folder-uri "vscode-remote://ssh-remote+$host/home/ubuntu"

# print your public IP, for allowed_cidr
myip:
    @curl -s https://checkip.amazonaws.com

# format the HCL
fmt:
    cd {{packer_dir}} && packer fmt .
    cd {{tf_dir}} && terraform fmt

# Indices currently marked stopped, read back out of the generated tfvars.
[private]
_stopped:
    @sed -n 's/^stopped_nodes *= *\[\(.*\)\]/\1/p' {{state_file}} 2>/dev/null | tr ',' ' '

# Applies the current config, but refuses if the plan would destroy anything.
# stop and start are lifecycle operations: no node should ever be replaced by
# one, and a silent replacement takes the root volume with it.
[private]
_apply:
    #!/usr/bin/env bash
    set -eu
    cd {{tf_dir}}
    trap 'rm -f .tfplan' EXIT
    terraform plan -input=false -out=.tfplan >/dev/null
    if terraform show -json .tfplan | grep -qE '"actions": *\[[^]]*"delete"'; then
        echo "refusing to apply: this plan destroys or replaces a resource." >&2
        echo "inspect it with: cd {{tf_dir}} && terraform plan" >&2
        exit 1
    fi
    terraform apply -input=false .tfplan

# Fails unless every argument is an index of a node that actually exists.
[private]
_check +nodes:
    #!/usr/bin/env bash
    set -eu
    count=$(cd {{tf_dir}} && terraform output -raw node_count 2>/dev/null) \
        || { echo "cannot read node_count: run 'just up' first" >&2; exit 1; }
    for n in {{nodes}}; do
        case $n in ''|*[!0-9]*) echo "not a node index: $n" >&2; exit 1 ;; esac
        [ "$n" -lt "$count" ] \
            || { echo "no such node: $n (have 0..$((count - 1)))" >&2; exit 1; }
    done

# Mirrors the key and one host entry per running node into the Windows ssh config.
# `code` in WSL is the Windows CLI on /mnt/c, so Remote-SSH runs Windows-side and
# reads that config, not this one. Host keys are discarded because a rebuilt node
# reuses an address with a new key.
[private]
_sshsync:
    #!/usr/bin/env bash
    set -eu
    win_ssh="$(wslpath "$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r')")/.ssh"
    mkdir -p "$win_ssh"

    # Copied, not referenced: Windows OpenSSH reads a key on the WSL mount as
    # world-readable and ignores it. The copy inherits the .ssh ACL, which it accepts.
    # `install` over `cp` so the 0400 source does not land as a read-only file that
    # the next run cannot overwrite.
    install -m 600 "$(cd {{tf_dir}} && terraform output -raw pem)" "$win_ssh/devstation.pem"
    pem=$(wslpath -w "$win_ssh/devstation.pem")

    {
        echo "# Generated by 'just code'. Rewritten on every run; do not edit."
        cd {{tf_dir}} && terraform output -json nodes | jq -r --arg pem "$pem" '
            to_entries[] | select(.value != "stopped")
            | "\nHost \(.key)\n  HostName \(.value)\n  User ubuntu\n  IdentityFile \($pem)\n  IdentitiesOnly yes\n  StrictHostKeyChecking no\n  UserKnownHostsFile NUL"'
    } > "$win_ssh/devstation.config"

    # Prepended once, then left alone: the rest of that file is hand-written.
    if ! grep -qxF 'Include devstation.config' "$win_ssh/config" 2>/dev/null; then
        tmp=$(mktemp)
        printf 'Include devstation.config\n\n' > "$tmp"
        cat "$win_ssh/config" >> "$tmp" 2>/dev/null || true
        mv "$tmp" "$win_ssh/config"
    fi
